name: Build release images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      GITHUB_REPO_OWNER: flighttrackr
      DOCKER_HUB_ORGANISATION: flighttrackr
      DOCKER_HUB_REPOSITORY: soapysdr-rtlsdr
      QEMU_PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386
      SoapySDR_RTLSDR_Repository: https://github.com/pothosware/SoapyRTLSDR.git
      SoapySDR_RTLSDR_Commit: 53ee8f4a19dd97011a569cfc2e6f7ad63f896100
    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKER_IMAGE: alpine3.13
          - DOCKER_IMAGE: alpine3.14
            IS_LATEST: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.DOCKER_IMAGE }}-latest-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.DOCKER_IMAGE }}-latest-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: ${{ env.QEMU_PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPOSITORY }}
          flavor: latest=${{ matrix.IS_LATEST == 'true' }}
          tags: type=raw,value=${{ matrix.DOCKER_IMAGE }}

      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ${{ matrix.DOCKER_IMAGE }}
          build-args: |
            SoapySDR_RTLSDR_Repository=${{ env.SoapySDR_RTLSDR_Repository }}
            SoapySDR_RTLSDR_Commit=${{ env.SoapySDR_RTLSDR_Commit }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          file: ${{ matrix.DOCKER_IMAGE }}/Dockerfile
          platforms: ${{ env.QEMU_PLATFORMS }}
          pull: true
          push: ${{ github.repository_owner == env.GITHUB_REPO_OWNER }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
